import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../components/DashboardNavbar";
import { AnimatedGrid } from "../components/AnimateGrid";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Findinit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black antialiased`}
      >
        <Navbar />
        <AnimatedGrid>{children}</AnimatedGrid>
        <Footer />
      </body>
    </html>
  );
}
